"""token

Revision ID: 3ca5d63585f9
Revises: 73a13d10af8e
Create Date: 2016-12-12 05:48:58.805543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ca5d63585f9'
down_revision = '73a13d10af8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=False))
    op.drop_index('token', table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('token', 'users', ['token'], unique=True)
    op.drop_column('users', 'username')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
